### ISSUE TITLE
Deploy to Bluemix doesn't work

### ISSUE THREAD

**Issue by pjam76** [watson-developer-cloud/nests#6]
When you click on Deploy to BLuemix, it goes through the process and fails every time on Deployment. 
Even after editing the manifest file, the build.xml,  it still has issues with webApp.war and not finding it.

**Comment by boazdavid** [comment]
Can you please share the error message you get?

**Comment by pjam76** [comment]
I stopped using Bluemix and moved over to Azure and AWS,  but essentially I'd click on Deploy to BlueMix and it would work all the way up till Deployment.   At that point it failed.   I will have to get back into IBM bluemix to see what the exact error message was.

**Comment by germanattanasio** [comment]
Fixed
